basePath: /
definitions:
  entity.Book:
    properties:
      author:
        $ref: "#/definitions/entity.Person"
      id:
        type: string
      summary:
        type: string
      title:
        type: string
    type: object
  entity.Person:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: ahmadaidin08.aa@gmail.com
    name: Ahmad Aidin
  description: This is a server for gonostic API.
  title: gonostic Service Documentation
  version: "1.0"
paths:
  /books:
    get:
      consumes:
        - application/json
      description: Find all books
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: "#/definitions/entity.Book"
            type: array
      summary: Find all books
      tags:
        - Book
swagger: "2.0"
